name: snake_identifier_ondevice
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pytorch_lite: ^1.1.0
  camera: ^0.11.0+1
  csv: ^6.0.0
  path_provider: ^2.0.11
  image: ^4.0.15
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/snake_model.ptl
    - assets/class_names.txt
    - assets/Snake_Names_And_Venom.csv